// AUTO-GENERATED by scripts/normalize-client-logos.mjs — do not edit by hand.
// Re-run `npm run clients:normalize` after changing the roster or raw logo files.

export interface ClientLogo {
  slug: string;
  name: string;
  sector: { en: string; id: string };
  src: string;
  /** Display size in CSS px (files are exported @2x). */
  width: number;
  height: number;
  /** Testimonial-only marks that stay out of the TrustedBy marquee. */
  hidden?: boolean;
}

export const clientLogos: ClientLogo[] = [
  {
    slug: "campos",
    name: "Campos Law Firm",
    sector: { en: "Law Firm", id: "Firma Hukum" },
    src: "/clients/campos.png",
    width: 118,
    height: 44,
  },
  {
    slug: "palda",
    name: "Palda Solusi Sinergi",
    sector: { en: "Business Solutions", id: "Solusi Bisnis" },
    src: "/clients/palda.png",
    width: 111,
    height: 47,
  },
  {
    slug: "beego",
    name: "Beego",
    sector: { en: "Ride-Hailing", id: "Transportasi Online" },
    src: "/clients/beego.png",
    width: 128,
    height: 40,
  },
  {
    slug: "guruinovatif",
    name: "GuruInovatif",
    sector: { en: "EdTech", id: "EdTech" },
    src: "/clients/guruinovatif.png",
    width: 170,
    height: 25,
  },
  {
    slug: "warungbungapagi",
    name: "Warung BungaPagi",
    sector: { en: "F&B Ecosystem", id: "Ekosistem F&B" },
    src: "/clients/warungbungapagi.png",
    width: 170,
    height: 28,
  },
  {
    slug: "nontonkuy",
    name: "NontonKuy",
    sector: { en: "Streaming", id: "Streaming" },
    src: "/clients/nontonkuy.png",
    width: 165,
    height: 32,
  },
  {
    slug: "batugin",
    name: "Batugin",
    sector: { en: "Healthcare Products", id: "Produk Kesehatan" },
    src: "/logo-batugin.svg",
    width: 110,
    height: 48,
  },
  {
    slug: "kliktravelid",
    name: "Klik Travel ID",
    sector: { en: "Travel & Tours", id: "Travel & Wisata" },
    src: "/kliktravelid.png",
    width: 54,
    height: 38,
  },
  {
    slug: "neurox",
    name: "Neurox",
    sector: { en: "F&B Operating System", id: "Sistem Operasi F&B" },
    src: "/neurox-logo.webp",
    width: 130,
    height: 38,
  },
];
