// AUTO-GENERATED by scripts/normalize-client-logos.mjs — do not edit by hand.
// Re-run `npm run clients:normalize` after changing the roster or raw logo files.

export interface ClientLogo {
  slug: string;
  name: string;
  sector: { en: string; id: string };
  src: string;
  /** Display size in CSS px (files are exported @2x). */
  width: number;
  height: number;
  /** Testimonial-only marks that stay out of the TrustedBy marquee. */
  hidden?: boolean;
}

export const clientLogos: ClientLogo[] = [
  {
    slug: "masterdiskon",
    name: "MasterDiskon",
    sector: { en: "Travel Platform", id: "Platform Travel" },
    src: "/clients/masterdiskon.png",
    width: 111,
    height: 47,
  },
  {
    slug: "eureka",
    name: "Eureka Group",
    sector: { en: "Logistics Group", id: "Grup Logistik" },
    src: "/clients/eureka.png",
    width: 116,
    height: 45,
  },
  {
    slug: "race",
    name: "RACE Raja Cepat",
    sector: { en: "Express Logistics", id: "Logistik Ekspres" },
    src: "/clients/race.png",
    width: 83,
    height: 63,
  },
  {
    slug: "campos",
    name: "Campos Law Firm",
    sector: { en: "Law Firm", id: "Firma Hukum" },
    src: "/clients/campos.png",
    width: 118,
    height: 44,
  },
  {
    slug: "jaja",
    name: "Jaja.id",
    sector: { en: "Marketplace", id: "Marketplace" },
    src: "/clients/jaja.png",
    width: 114,
    height: 45,
  },
  {
    slug: "palda",
    name: "Palda Solusi Sinergi",
    sector: { en: "Business Solutions", id: "Solusi Bisnis" },
    src: "/clients/palda.png",
    width: 111,
    height: 47,
  },
  {
    slug: "beego",
    name: "Beego",
    sector: { en: "Ride-Hailing", id: "Transportasi Online" },
    src: "/clients/beego.png",
    width: 128,
    height: 40,
  },
  {
    slug: "guruinovatif",
    name: "GuruInovatif",
    sector: { en: "EdTech", id: "EdTech" },
    src: "/clients/guruinovatif.png",
    width: 170,
    height: 25,
  },
  {
    slug: "warungbungapagi",
    name: "Warung BungaPagi",
    sector: { en: "F&B Ecosystem", id: "Ekosistem F&B" },
    src: "/clients/warungbungapagi.png",
    width: 170,
    height: 28,
  },
  {
    slug: "nontonkuy",
    name: "NontonKuy",
    sector: { en: "Streaming", id: "Streaming" },
    src: "/clients/nontonkuy.png",
    width: 165,
    height: 32,
  },
  {
    slug: "elogs",
    name: "Eureka Logistics",
    sector: { en: "Logistics Platform", id: "Platform Logistik" },
    src: "/clients/elogs.png",
    width: 117,
    height: 45,
    hidden: true,
  },
];
